name: 'Update Prior Information'

on:
  schedule:
    - cron: "0 12 * * *"
jobs:
  update_election:
    runs-on: macos-latest
    steps:
      - name: Setup
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.SECRETS }}
      - name: Get Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run data pipeline script
        run: |
          python data_pipe.py
        shell: bash
      - name: Update datasets
        uses: test-room-7/action-update-file@v1
        with:
            # Include all csv files from the `data` directory
            file-path: |
              data/*.csv
              figures/*.png
            commit-msg: Update Prior Beliefs
            github-token: ${{ secrets.SECRETS }}